<a href="https://colab.research.google.com/github/gkkhnyldz/P.I.-Works/blob/main/quest%C4%B1on4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:

import numpy as np
import pandas as pd
ourdata = pd.read_csv("country_vaccination_stats.csv")
def impute_by_min(country):
    country__data = ourdata[ourdata["country"] == country]
    min_vaccinations = country__data["daily_vaccinations"].min()
    ourdata.loc[(ourdata["country"] == country) & (ourdata["daily_vaccinations"].isna()), "daily_vaccinations"] = min_vaccinations
    ourdata.loc[(ourdata["country"] == country) & (ourdata["daily_vaccinations"].isnull()), "daily_vaccinations"] = 0

countries = ourdata["country"].unique()
for country in countries:
    impute_by_min(country)

In [9]:
ourdata

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,6483.0,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"